
--
-- constants to strings.
--

function GetEnumerations()
  local E = {
    ["ActionResult"] = {
      [ACTION_RESULT_ABILITY_ON_COOLDOWN]   = "AbilityOnCooldown",
      [ACTION_RESULT_ABSORBED]              = "Absorbed",
      [ACTION_RESULT_BAD_TARGET]            = "BadTarget",
      [ACTION_RESULT_BEGIN]                 = "Begin",
      [ACTION_RESULT_BEGIN_CHANNEL]         = "Begin_Channel",
      [ACTION_RESULT_BLADETURN]             = "Bladeturn",
      [ACTION_RESULT_BLOCKED]               = "Blocked",
      [ACTION_RESULT_BLOCKED_DAMAGE]        = "BlockedDamage",
      [ACTION_RESULT_BUFF]                  = "Buff",
      [ACTION_RESULT_BUSY]                  = "Busy",
      [ACTION_RESULT_CANNOT_USE]            = "CannotUse",
      [ACTION_RESULT_CANT_SEE_TARGET]       = "CantSeeTarget",
      [ACTION_RESULT_CASTER_DEAD]           = "CasterDead",
      [ACTION_RESULT_COMPLETE]              = "Complete",
      [ACTION_RESULT_CRITICAL_DAMAGE]       = "CriticalDamage",
      [ACTION_RESULT_CRITICAL_HEAL]         = "CriticalHeal",
      [ACTION_RESULT_DAMAGE]                = "DAMAGE",
      [ACTION_RESULT_DAMAGE_SHIELDED]       = "DAMAGE_SHIELDED",
      [ACTION_RESULT_DEBUFF]                = "DEBUFF",
      [ACTION_RESULT_DEFENDED]              = "DEFENDED",
      [ACTION_RESULT_DIED]                  = "DIED",
      [ACTION_RESULT_DIED_XP]               = "DIED_XP",
      [ACTION_RESULT_DISARMED]              = "DISARMED",
      [ACTION_RESULT_DISORIENTED]           = "DISORIENTED",
      [ACTION_RESULT_DODGED]                = "DODGED",
      [ACTION_RESULT_DOT_TICK]              = "DOT_TICK",
      [ACTION_RESULT_DOT_TICK_CRITICAL]     = "DOT_TICK_CRITICAL",
      [ACTION_RESULT_EFFECT_FADED]          = "EFFECT_FADED",
      [ACTION_RESULT_EFFECT_GAINED]         = "EFFECT_GAINED",
      [ACTION_RESULT_EFFECT_GAINED_DURATION] = "EFFECT_GAINED_DURATION",
      [ACTION_RESULT_FAILED]                = "FAILED",
      [ACTION_RESULT_FAILED_REQUIREMENTS] = "FAILED_REQUIREMENTS",
      [ACTION_RESULT_FAILED_SIEGE_CREATION_REQUIREMENTS] = "FAILED_SIEGE_CREATION_REQUIREMENTS",
      [ACTION_RESULT_FALLING]               = "FALLING",
      [ACTION_RESULT_FALL_DAMAGE]           = "FALL_DAMAGE",
      [ACTION_RESULT_FEARED]                = "FEARED",
      [ACTION_RESULT_GRAVEYARD_DISALLOWED_IN_INSTANCE] = "GRAVEYARD_DISALLOWED_IN_INSTANCE",
      [ACTION_RESULT_GRAVEYARD_TOO_CLOSE]   = "GRAVEYARD_TOO_CLOSE",
      [ACTION_RESULT_HEAL]                  = "HEAL",
      [ACTION_RESULT_HOT_TICK]              = "HOT_TICK",
      [ACTION_RESULT_HOT_TICK_CRITICAL]     = "HOT_TICK_CRITICAL",
      [ACTION_RESULT_IMMUNE]                = "IMMUNE",
      [ACTION_RESULT_INSUFFICIENT_RESOURCE] = "INSUFFICIENT_RESOURCE",
      [ACTION_RESULT_INTERCEPTED]           = "INTERCEPTED",
      [ACTION_RESULT_INTERRUPT]             = "INTERRUPT",
      [ACTION_RESULT_INVALID]               = "INVALID",
      [ACTION_RESULT_INVALID_FIXTURE]       = "INVALID_FIXTURE",
      [ACTION_RESULT_INVALID_TERRAIN]       = "INVALID_TERRAIN",
      [ACTION_RESULT_IN_COMBAT]             = "IN_COMBAT",
      [ACTION_RESULT_IN_ENEMY_KEEP]         = "IN_ENEMY_KEEP",
      [ACTION_RESULT_KILLING_BLOW]          = "KILLING_BLOW",
      [ACTION_RESULT_LEVITATED]             = "LEVITATED",
      [ACTION_RESULT_LINKED_CAST]           = "LINKED_CAST",
      [ACTION_RESULT_MISS]                  = "MISS",
      [ACTION_RESULT_MISSING_EMPTY_SOUL_GEM] = "MISSING_EMPTY_SOUL_GEM",
      [ACTION_RESULT_MISSING_FILLED_SOUL_GEM] = "MISSING_FILLED_SOUL_GEM",
      [ACTION_RESULT_MOUNTED]               = "MOUNTED",
      [ACTION_RESULT_MUST_BE_IN_OWN_KEEP]   = "MUST_BE_IN_OWN_KEEP",
      [ACTION_RESULT_NOT_ENOUGH_INVENTORY_SPACE] = "NOT_ENOUGH_INVENTORY_SPACE",
      [ACTION_RESULT_NO_LOCATION_FOUND]     = "NO_LOCATION_FOUND",
      [ACTION_RESULT_NO_RAM_ATTACKABLE_TARGET_WITHIN_RANGE] = "NO_RAM_ATTACKABLE_TARGET_WITHIN_RANGE",
      [ACTION_RESULT_NPC_TOO_CLOSE]         = "NPC_TOO_CLOSE",
      [ACTION_RESULT_OFFBALANCE]            = "OFFBALANCE",
      [ACTION_RESULT_PACIFIED]              = "PACIFIED",
      [ACTION_RESULT_PARRIED]               = "PARRIED",
      [ACTION_RESULT_PARTIAL_RESIST]        = "PARTIAL_RESIST",
      [ACTION_RESULT_POWER_DRAIN]           = "POWER_DRAIN",
      [ACTION_RESULT_POWER_ENERGIZE]        = "POWER_ENERGIZE",
      [ACTION_RESULT_PRECISE_DAMAGE]        = "PRECISE_DAMAGE",
      [ACTION_RESULT_QUEUED]                = "QUEUED",
      [ACTION_RESULT_RAM_ATTACKABLE_TARGETS_ALL_DESTROYED] = "RAM_ATTACKABLE_TARGETS_ALL_DESTROYED",
      [ACTION_RESULT_RAM_ATTACKABLE_TARGETS_ALL_OCCUPIED] = "RAM_ATTACKABLE_TARGETS_ALL_OCCUPIED",
      [ACTION_RESULT_REFLECTED]             = "REFLECTED",
      [ACTION_RESULT_REINCARNATING]         = "REINCARNATING",
      [ACTION_RESULT_RESIST]                = "RESIST",
      [ACTION_RESULT_RESURRECT]             = "RESURRECT",
      [ACTION_RESULT_ROOTED]                = "ROOTED",
      [ACTION_RESULT_SIEGE_LIMIT]           = "SIEGE_LIMIT",
      [ACTION_RESULT_SIEGE_TOO_CLOSE]       = "SIEGE_TOO_CLOSE",
      [ACTION_RESULT_SILENCED]              = "Silenced",
      [ACTION_RESULT_SPRINTING]             = "Sprinting",
      [ACTION_RESULT_STAGGERED]             = "Staggered",
      [ACTION_RESULT_STUNNED]               = "Stunned",
      [ACTION_RESULT_SWIMMING]              = "Swimming",
      [ACTION_RESULT_TARGET_DEAD]           = "TargetDead",
      [ACTION_RESULT_TARGET_NOT_IN_VIEW]    = "TargetNotInView",
      [ACTION_RESULT_TARGET_NOT_PVP_FLAGGED] = "TargetNotPvpFlagged",
      [ACTION_RESULT_TARGET_OUT_OF_RANGE]   = "TargetOutOfRange",
      [ACTION_RESULT_TARGET_TOO_CLOSE]      = "TargetTooClose",
      [ACTION_RESULT_UNEVEN_TERRAIN]        = "UnevenTerrain",
      [ACTION_RESULT_WEAPONSWAP]            = "WEAPONSWAP",
      [ACTION_RESULT_WRECKING_DAMAGE]       = "WreckingDamage",
      [ACTION_RESULT_WRONG_WEAPON]          = "WrongWeapon"
    },
    
    ["ActionSlotType"] = {
      [ACTION_SLOT_TYPE_BLOCK]          = "Block",
      [ACTION_SLOT_TYPE_HEAVY_ATTACK]   = "HeavyAttack",
      [ACTION_SLOT_TYPE_LIGHT_ATTACK]   = "LightAttack",
      [ACTION_SLOT_TYPE_NORMAL_ABILITY] = "NormalAbility",
      [ACTION_SLOT_TYPE_OTHER]          = "Other",
      [ACTION_SLOT_TYPE_ULTIMATE]       = "Ultimate",
      [ACTION_SLOT_TYPE_WEAPON_ATTACK]  = "WeaponAttack"
    },

    ["CombatUnitType"] = {
      [COMBAT_UNIT_TYPE_GROUP]      = "Group",
      [COMBAT_UNIT_TYPE_NONE]       = "None",
      [COMBAT_UNIT_TYPE_OTHER]      = "Other",
      [COMBAT_UNIT_TYPE_PLAYER]     = "Player",
      [COMBAT_UNIT_TYPE_PLAYER_PET] = "PPet"
    },

    ["PowerType"] = {
      [POWERTYPE_FINESSE]       = "Finesse",
      [POWERTYPE_HEALTH]        = "Health",
      [POWERTYPE_INVALID]       = "Invalid",
      [POWERTYPE_MAGICKA]       = "Magicka",
      [POWERTYPE_MOUNT_STAMINA] = "MountStamina",
      [POWERTYPE_STAMINA]       = "Stamina",
      [POWERTYPE_ULTIMATE]      = "Ultimate",
      [POWERTYPE_WEREWOLF]      = "Werewolf"
    },

    ["DamageType"] = {
      [DAMAGE_TYPE_COLD]        = "Cold",
      [DAMAGE_TYPE_DISEASE]     = "Disease",
      [DAMAGE_TYPE_DROWN]       = "Drown",
      [DAMAGE_TYPE_EARTH]       = "Earth",
      [DAMAGE_TYPE_FIRE]        = "Fire",
      [DAMAGE_TYPE_GENERIC]     = "Generic",
      [DAMAGE_TYPE_MAGIC]       = "Magic",
      [DAMAGE_TYPE_NONE]        = "None",
      [DAMAGE_TYPE_OBLIVION]    = "Oblivion",
      [DAMAGE_TYPE_PHYSICAL]    = "Physical",
      [DAMAGE_TYPE_POISON]      = "Poison",
      [DAMAGE_TYPE_SHOCK]       = "Shock"
    }
  }

  return E
end
